





 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("3.4.7.0")]
 [assembly: AssemblyFileVersion("3.4.7.0")]